# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Teecee-Coder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Teecee-Coder
  pod 'SwiftSocket'
pod 'Alamofire'

  target 'Teecee-CoderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Teecee-CoderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
